#! /bin/sh
set -eu

_is_separator() {
    echo "${1}" | grep -E '^###' >/dev/null
}

code=""
program=""

context=text
while read -r line; do
    if [ "${context}" = "text" ]; then
        if _is_separator "${line}"; then
            context=code
            program="$( echo "${line}" | cut -d ' ' -f 3- )"
        else
            echo "${line}"
        fi
    else
        if _is_separator "${line}"; then
            context=text
            echo "${code}" | ${program}
            code=""
        else
            code="${code}\n${line}"
        fi
    fi
done
