#! /bin/sh
set -eu

beginswith() { case $2 in "$1"*) true;; *) false;; esac; }

context=text
code=""
program=""

while read -r line; do
    if [ "${context}" = "text" ]; then
        if beginswith "<?paco" "${line}"; then
            context=code
            program="$( echo "${line}" | cut -d ' ' -f 3- )"
        else
            echo "${line}"
        fi
    else
        if beginswith "?>" ${line}; then
            context=text
            echo "${code}" | ${program}
            code=""
        else
            code="${code}\n${line}"
        fi
    fi
done
