#! /bin/sh
set -eu

_is_separator() {
    echo "${1}" | grep -E '^###' >/dev/null
}

code="$(mktemp)"
chmod +x "${code}"

context=text
while read -r line; do
    if [ "${context}" = "text" ]; then
        if _is_separator "${line}"; then
            context=code
        else
            echo "${line}"
        fi
    else
        if _is_separator "${line}"; then
            context=text
            "${code}"
            printf "" > "${code}"
        else
            echo ${line} >> "${code}"
        fi
    fi
done
